# -*- coding: utf-8 -*-
"""
Bank soal UAS Penganggaran Perusahaan - Pertemuan 9-14.
Sumber: RPS Penganggaran Perusahaan, Ardiansyah Japlani, S.E., M.B.A.
Program Studi S1 Kewirausahaan, FEB Universitas Muhammadiyah Metro.

Cakupan: Anggaran Biaya Operasional, Anggaran Kas, Anggaran Piutang & Kredit,
Anggaran Modal (Payback/NPV/IRR), Anggaran Induk (Master Budget), Analisis Varian.

Total 100 soal. Tiap mahasiswa (dari 10 mahasiswa) menerima 20 soal acak
berdasarkan NPM; opsi jawaban diacak ulang per NPM.
Soal konsep ditulis manual; soal hitung dibangkitkan dan diverifikasi Python.
"""

DURASI_UAS_MENIT = 15
JUMLAH_SOAL_PER_MAHASISWA = 20
JUMLAH_MAHASISWA = 10
ACAK_OPSI = True

UAS_BANK = [
    {"q": "Anggaran biaya operasional pada penganggaran perusahaan mencakup...", "o": ["Biaya pemasaran dan biaya administrasi umum", "Biaya bahan baku langsung", "Biaya tenaga kerja produksi", "Harga pokok produksi"], "a": 0},
    {"q": "Yang termasuk komponen biaya pemasaran adalah...", "o": ["Iklan, distribusi, dan komisi penjualan", "Gaji staf kantor", "Sewa gudang produksi", "Bahan baku"], "a": 0},
    {"q": "Yang termasuk biaya administrasi dan umum adalah...", "o": ["Gaji staf dan sewa kantor", "Iklan dan promosi", "Komisi penjualan", "Biaya distribusi"], "a": 0},
    {"q": "Anggaran biaya operasional disusun untuk...", "o": ["Merencanakan biaya penjualan dan administrasi per periode", "Menghitung bahan baku", "Menyusun jadwal produksi", "Menentukan tarif upah langsung"], "a": 0},
    {"q": "Biaya komisi penjualan tergolong biaya...", "o": ["Pemasaran", "Administrasi umum", "Overhead pabrik", "Bahan baku"], "a": 0},
    {"q": "Dalam bisnis digital dan startup, anggaran biaya pemasaran relevan karena...", "o": ["Belanja iklan digital menjadi komponen biaya yang besar", "Tidak ada biaya sama sekali", "Hanya biaya produksi yang penting", "Pemasaran tidak dianggarkan"], "a": 0},
    {"q": "Sewa kantor dan gaji staf administrasi dianggarkan dalam...", "o": ["Anggaran biaya administrasi dan umum", "Anggaran bahan baku", "Anggaran kas masuk", "Anggaran produksi"], "a": 0},
    {"q": "Tujuan menyusun anggaran biaya operasional adalah...", "o": ["Mengendalikan pengeluaran penjualan dan administrasi", "Menaikkan harga jual otomatis", "Menghapus biaya tetap", "Mengabaikan biaya"], "a": 0},
    {"q": "Anggaran kas (cash budget) berisi rencana...", "o": ["Penerimaan kas, pengeluaran kas, dan saldo kas", "Laba rugi tahunan", "Persediaan barang jadi", "Standar jam kerja"], "a": 0},
    {"q": "Pentingnya anggaran kas bagi usaha adalah...", "o": ["Menjaga kelangsungan usaha dengan memastikan likuiditas", "Menaikkan laba akuntansi", "Menghapus utang", "Mengganti neraca"], "a": 0},
    {"q": "Saldo kas akhir dihitung dengan rumus...", "o": ["Saldo awal + penerimaan - pengeluaran", "Penerimaan - laba", "Saldo awal + laba bersih", "Pengeluaran - penerimaan"], "a": 0},
    {"q": "Kebijakan saldo kas minimum berguna untuk...", "o": ["Menjaga cadangan likuiditas dan mengantisipasi defisit", "Menaikkan biaya", "Menghapus penerimaan", "Menambah persediaan"], "a": 0},
    {"q": "Ketika anggaran kas menunjukkan defisit, perusahaan dapat...", "o": ["Merencanakan pembiayaan (pinjaman) untuk menutup kekurangan", "Mengabaikan defisit", "Menghentikan pencatatan", "Menaikkan harga tanpa dasar"], "a": 0},
    {"q": "Contoh penerimaan kas dalam cash budget adalah...", "o": ["Penjualan tunai dan penagihan piutang", "Pembelian bahan baku", "Pembayaran gaji", "Pelunasan utang"], "a": 0},
    {"q": "Contoh pengeluaran kas dalam cash budget adalah...", "o": ["Pembayaran gaji dan pembelian bahan baku", "Penjualan tunai", "Penerimaan piutang", "Setoran modal"], "a": 0},
    {"q": "Anggaran kas termasuk kelompok anggaran...", "o": ["Keuangan", "Operasional produksi", "Bahan baku", "Tenaga kerja"], "a": 0},
    {"q": "Anggaran piutang berkaitan erat dengan...", "o": ["Anggaran penjualan (khususnya penjualan kredit)", "Anggaran bahan baku", "Anggaran overhead", "Anggaran tenaga kerja"], "a": 0},
    {"q": "Pola penagihan piutang (collection pattern) menggambarkan...", "o": ["Persentase penjualan kredit yang tertagih tiap periode", "Jumlah bahan baku", "Kapasitas produksi", "Tarif upah"], "a": 0},
    {"q": "Kebijakan kredit usaha umumnya mencakup...", "o": ["Syarat pembayaran, diskon, dan periode kredit", "Standar bahan baku", "Tarif overhead", "Jam kerja langsung"], "a": 0},
    {"q": "Piutang tak tertagih (bad debt) adalah...", "o": ["Piutang yang diperkirakan tidak dapat ditagih", "Kas yang diterima penuh", "Persediaan rusak", "Utang perusahaan"], "a": 0},
    {"q": "Schedule penerimaan kas dari piutang berguna untuk...", "o": ["Memperkirakan kas masuk dari penjualan kredit tiap periode", "Menghitung laba kotor", "Menyusun jadwal produksi", "Menetapkan tarif upah"], "a": 0},
    {"q": "Syarat kredit 2/10 net 30 berarti...", "o": ["Diskon 2 persen bila bayar dalam 10 hari, jatuh tempo 30 hari", "Bunga 2 persen per 10 hari", "Denda 10 persen", "Kredit 30 bulan"], "a": 0},
    {"q": "Semakin longgar kebijakan kredit, umumnya...", "o": ["Penjualan naik tetapi risiko piutang tak tertagih meningkat", "Penjualan turun", "Risiko piutang hilang", "Kas segera penuh"], "a": 0},
    {"q": "Manajemen risiko piutang bertujuan...", "o": ["Menekan kerugian akibat piutang tak tertagih", "Menaikkan bad debt", "Menghapus penjualan kredit", "Mengabaikan penagihan"], "a": 0},
    {"q": "Anggaran modal (capital expenditure budget) berkaitan dengan...", "o": ["Investasi jangka panjang (aset tetap/proyek besar)", "Pembelian bahan baku harian", "Gaji mingguan", "Biaya iklan bulanan"], "a": 0},
    {"q": "Metode evaluasi anggaran modal mencakup...", "o": ["Payback Period, NPV, dan IRR", "Analisis varian", "Collection pattern", "Tarif overhead"], "a": 0},
    {"q": "Payback Period mengukur...", "o": ["Lama waktu hingga investasi kembali dari arus kas", "Selisih kas masuk dan keluar", "Laba akuntansi", "Rasio piutang"], "a": 0},
    {"q": "Kaidah keputusan NPV adalah menerima proyek bila...", "o": ["NPV bernilai positif", "NPV bernilai negatif", "NPV nol", "Payback lama"], "a": 0},
    {"q": "Kaidah keputusan IRR adalah menerima proyek bila...", "o": ["IRR melebihi biaya modal", "IRR di bawah biaya modal", "IRR nol", "IRR negatif"], "a": 0},
    {"q": "Sumber pembiayaan capex (belanja modal) dapat berasal dari...", "o": ["Ekuitas atau utang jangka panjang", "Kas kecil harian", "Piutang dagang", "Persediaan"], "a": 0},
    {"q": "NPV mengukur...", "o": ["Selisih nilai sekarang arus kas masuk dan investasi", "Laba kotor tahunan", "Jumlah unit terjual", "Saldo kas minimum"], "a": 0},
    {"q": "Semakin pendek Payback Period, umumnya proyek dinilai...", "o": ["Lebih cepat mengembalikan modal sehingga lebih menarik", "Lebih berisiko selalu", "Pasti ditolak", "Tidak layak"], "a": 0},
    {"q": "Anggaran induk (master budget) adalah...", "o": ["Integrasi seluruh anggaran operasional dan keuangan perusahaan", "Anggaran kas saja", "Anggaran penjualan saja", "Laporan pajak"], "a": 0},
    {"q": "Master budget mengintegrasikan anggaran operasional ke dalam...", "o": ["Anggaran keuangan (laba rugi dan neraca proyeksi)", "Anggaran bahan baku saja", "Daftar hadir", "Struktur organisasi"], "a": 0},
    {"q": "Projected income statement merupakan bagian master budget yang menyajikan...", "o": ["Proyeksi laba rugi", "Proyeksi arus kas saja", "Daftar piutang", "Jadwal produksi"], "a": 0},
    {"q": "Projected balance sheet dalam master budget menyajikan...", "o": ["Proyeksi posisi keuangan (neraca)", "Proyeksi penjualan harian", "Tarif overhead", "Pola penagihan"], "a": 0},
    {"q": "Titik awal penyusunan master budget biasanya adalah...", "o": ["Anggaran penjualan", "Anggaran kas", "Neraca proyeksi", "Analisis varian"], "a": 0},
    {"q": "Master budget disebut terintegrasi karena...", "o": ["Setiap anggaran saling terkait dan bermuara pada laporan keuangan proyeksi", "Berdiri sendiri-sendiri", "Hanya berisi kas", "Tidak berhubungan"], "a": 0},
    {"q": "Komponen master budget terdiri atas...", "o": ["Anggaran operasional dan anggaran keuangan", "Hanya anggaran iklan", "Hanya anggaran gaji", "Hanya pajak"], "a": 0},
    {"q": "Analisis varian (variance analysis) membandingkan...", "o": ["Anggaran dengan realisasi aktual", "Dua perusahaan berbeda", "Harga pesaing", "Kapasitas mesin"], "a": 0},
    {"q": "Varian yang menguntungkan (favorable) terjadi ketika...", "o": ["Biaya aktual lebih rendah dari anggaran atau pendapatan lebih tinggi", "Biaya aktual lebih tinggi dari anggaran", "Pendapatan lebih rendah", "Tidak ada selisih"], "a": 0},
    {"q": "Varian yang tidak menguntungkan (unfavorable) terjadi ketika...", "o": ["Biaya aktual lebih tinggi dari anggaran atau pendapatan lebih rendah", "Biaya aktual lebih rendah", "Pendapatan lebih tinggi", "Realisasi sama dengan anggaran"], "a": 0},
    {"q": "Jenis varian yang dianalisis meliputi...", "o": ["Varian penjualan, bahan baku, tenaga kerja, dan overhead", "Varian cuaca", "Varian warna produk", "Varian jam istirahat"], "a": 0},
    {"q": "Laporan realisasi anggaran berguna untuk...", "o": ["Mengevaluasi kinerja dan mengendalikan penyimpangan", "Menaikkan anggaran otomatis", "Menghapus target", "Mengabaikan hasil"], "a": 0},
    {"q": "Tujuan akhir analisis varian adalah...", "o": ["Dasar pengambilan keputusan dan perbaikan anggaran berikutnya", "Menghukum karyawan", "Menutupi kesalahan", "Menghentikan evaluasi"], "a": 0},
    {"q": "Selisih realisasi terhadap anggaran disebut...", "o": ["Varian (variance)", "Laba kotor", "Margin kontribusi", "Saldo kas"], "a": 0},
    {"q": "Penyusunan anggaran yang jujur dan dapat dipertanggungjawabkan mencerminkan nilai profetik...", "o": ["Amanah dan shiddiq", "Riya", "Takabur", "Israf"], "a": 0},
    {"q": "Anggaran sebagai alat pengendalian sejalan dengan prinsip Islam untuk...", "o": ["Muhasabah (evaluasi diri) atas apa yang telah diperbuat", "Menimbun harta", "Berlebih-lebihan", "Menghindari perencanaan"], "a": 0},
    {"q": "Software yang dianjurkan RPS untuk menyusun template anggaran adalah...", "o": ["Ms Excel dan Google Sheets", "Game online", "Aplikasi musik", "Editor video"], "a": 0},
    {"q": "Saldo kas awal Rp5 juta, penerimaan kas Rp40 juta, pengeluaran kas Rp47 juta. Saldo kas akhir adalah...", "o": ["-7 juta", "92 juta", "12 juta", "-2 juta"], "a": 3},
    {"q": "Saldo kas awal Rp15 juta, penerimaan kas Rp55 juta, pengeluaran kas Rp46 juta. Saldo kas akhir adalah...", "o": ["116 juta", "9 juta", "24 juta", "6 juta"], "a": 2},
    {"q": "Saldo kas awal Rp15 juta, penerimaan kas Rp25 juta, pengeluaran kas Rp22 juta. Saldo kas akhir adalah...", "o": ["12 juta", "62 juta", "18 juta", "3 juta"], "a": 2},
    {"q": "Saldo kas awal Rp5 juta, penerimaan kas Rp51 juta, pengeluaran kas Rp35 juta. Saldo kas akhir adalah...", "o": ["21 juta", "16 juta", "-11 juta", "91 juta"], "a": 0},
    {"q": "Saldo kas awal Rp10 juta, penerimaan kas Rp42 juta, pengeluaran kas Rp39 juta. Saldo kas akhir adalah...", "o": ["7 juta", "91 juta", "3 juta", "13 juta"], "a": 3},
    {"q": "Saldo kas awal Rp5 juta, penerimaan kas Rp55 juta, pengeluaran kas Rp49 juta. Saldo kas akhir adalah...", "o": ["11 juta", "-1 juta", "109 juta", "6 juta"], "a": 0},
    {"q": "Saldo kas awal Rp8 juta, penerimaan kas Rp56 juta, pengeluaran kas Rp34 juta. Saldo kas akhir adalah...", "o": ["-14 juta", "98 juta", "22 juta", "30 juta"], "a": 3},
    {"q": "Saldo kas awal Rp10 juta, penerimaan kas Rp49 juta, pengeluaran kas Rp42 juta. Saldo kas akhir adalah...", "o": ["3 juta", "7 juta", "101 juta", "17 juta"], "a": 3},
    {"q": "Saldo kas awal Rp5 juta, penerimaan kas Rp47 juta, pengeluaran kas Rp47 juta. Saldo kas akhir adalah...", "o": ["5 juta", "0 juta", "99 juta", "5 juta "], "a": 0},
    {"q": "Saldo kas awal Rp12 juta, penerimaan kas Rp56 juta, pengeluaran kas Rp45 juta. Saldo kas akhir adalah...", "o": ["113 juta", "1 juta", "11 juta", "23 juta"], "a": 3},
    {"q": "Saldo kas awal Rp8 juta, penerimaan kas Rp23 juta, pengeluaran kas Rp48 juta. Saldo kas akhir adalah...", "o": ["33 juta", "79 juta", "-25 juta", "-17 juta"], "a": 3},
    {"q": "Saldo kas awal Rp12 juta, penerimaan kas Rp29 juta, pengeluaran kas Rp45 juta. Saldo kas akhir adalah...", "o": ["-16 juta", "28 juta", "-4 juta", "86 juta"], "a": 2},
    {"q": "Saldo kas awal Rp20 juta, penerimaan kas Rp50 juta, pengeluaran kas Rp49 juta. Saldo kas akhir adalah...", "o": ["21 juta", "119 juta", "19 juta", "1 juta"], "a": 0},
    {"q": "Saldo kas awal Rp20 juta, penerimaan kas Rp39 juta, pengeluaran kas Rp50 juta. Saldo kas akhir adalah...", "o": ["9 juta", "-11 juta", "109 juta", "31 juta"], "a": 0},
    {"q": "Saldo kas akhir sebelum pembiayaan Rp2 juta, sedangkan saldo kas minimum yang ditetapkan Rp10 juta. Apa yang perlu dilakukan?", "o": ["Membagikan seluruh kas sebagai laba", "Menaikkan harga jual dua kali lipat", "Mencari pembiayaan minimal Rp8 juta", "Menghentikan operasi usaha"], "a": 2},
    {"q": "Saldo kas akhir sebelum pembiayaan Rp-1 juta, sedangkan saldo kas minimum yang ditetapkan Rp15 juta. Apa yang perlu dilakukan?", "o": ["Mencari pembiayaan minimal Rp16 juta", "Membagikan seluruh kas sebagai laba", "Menghentikan operasi usaha", "Menaikkan harga jual dua kali lipat"], "a": 0},
    {"q": "Saldo kas akhir sebelum pembiayaan Rp13 juta, sedangkan saldo kas minimum yang ditetapkan Rp5 juta. Apa yang perlu dilakukan?", "o": ["Tidak perlu pembiayaan karena saldo di atas minimum", "Membagikan seluruh kas sebagai laba", "Menaikkan harga jual dua kali lipat", "Menghentikan operasi usaha"], "a": 0},
    {"q": "Saldo kas akhir sebelum pembiayaan Rp19 juta, sedangkan saldo kas minimum yang ditetapkan Rp15 juta. Apa yang perlu dilakukan?", "o": ["Menghentikan operasi usaha", "Tidak perlu pembiayaan karena saldo di atas minimum", "Membagikan seluruh kas sebagai laba", "Menaikkan harga jual dua kali lipat"], "a": 1},
    {"q": "Saldo kas akhir sebelum pembiayaan Rp8 juta, sedangkan saldo kas minimum yang ditetapkan Rp10 juta. Apa yang perlu dilakukan?", "o": ["Menghentikan operasi usaha", "Membagikan seluruh kas sebagai laba", "Mencari pembiayaan minimal Rp2 juta", "Menaikkan harga jual dua kali lipat"], "a": 2},
    {"q": "Saldo kas akhir sebelum pembiayaan Rp22 juta, sedangkan saldo kas minimum yang ditetapkan Rp10 juta. Apa yang perlu dilakukan?", "o": ["Menghentikan operasi usaha", "Membagikan seluruh kas sebagai laba", "Tidak perlu pembiayaan karena saldo di atas minimum", "Menaikkan harga jual dua kali lipat"], "a": 2},
    {"q": "Saldo kas akhir sebelum pembiayaan Rp20 juta, sedangkan saldo kas minimum yang ditetapkan Rp5 juta. Apa yang perlu dilakukan?", "o": ["Tidak perlu pembiayaan karena saldo di atas minimum", "Menaikkan harga jual dua kali lipat", "Membagikan seluruh kas sebagai laba", "Menghentikan operasi usaha"], "a": 0},
    {"q": "Saldo kas akhir sebelum pembiayaan Rp-4 juta, sedangkan saldo kas minimum yang ditetapkan Rp5 juta. Apa yang perlu dilakukan?", "o": ["Menghentikan operasi usaha", "Membagikan seluruh kas sebagai laba", "Mencari pembiayaan minimal Rp9 juta", "Menaikkan harga jual dua kali lipat"], "a": 2},
    {"q": "Penjualan kredit bulan ini Rp50 juta. Bila 60 persen tertagih pada bulan yang sama, berapa kas yang diterima dari penjualan tersebut bulan ini?", "o": ["20 juta", "40 juta", "50 juta", "30 juta"], "a": 3},
    {"q": "Penjualan kredit bulan ini Rp150 juta. Bila 70 persen tertagih pada bulan yang sama, berapa kas yang diterima dari penjualan tersebut bulan ini?", "o": ["115 juta", "45 juta", "105 juta", "150 juta"], "a": 2},
    {"q": "Penjualan kredit bulan ini Rp150 juta. Bila 75 persen tertagih pada bulan yang sama, berapa kas yang diterima dari penjualan tersebut bulan ini?", "o": ["150 juta", "122 juta", "112 juta", "37 juta"], "a": 2},
    {"q": "Penjualan kredit bulan ini Rp100 juta. Bila 80 persen tertagih pada bulan yang sama, berapa kas yang diterima dari penjualan tersebut bulan ini?", "o": ["90 juta", "80 juta", "20 juta", "100 juta"], "a": 1},
    {"q": "Penjualan kredit bulan ini Rp120 juta. Bila 70 persen tertagih pada bulan yang sama, berapa kas yang diterima dari penjualan tersebut bulan ini?", "o": ["94 juta", "120 juta", "84 juta", "36 juta"], "a": 2},
    {"q": "Penjualan kredit bulan ini Rp80 juta. Bila 70 persen tertagih pada bulan yang sama, berapa kas yang diterima dari penjualan tersebut bulan ini?", "o": ["56 juta", "80 juta", "66 juta", "24 juta"], "a": 0},
    {"q": "Penjualan kredit bulan ini Rp50 juta. Bila 80 persen tertagih pada bulan yang sama, berapa kas yang diterima dari penjualan tersebut bulan ini?", "o": ["10 juta", "50 juta", "50 juta ", "40 juta"], "a": 3},
    {"q": "Penjualan kredit bulan ini Rp100 juta. Bila 60 persen tertagih pada bulan yang sama, berapa kas yang diterima dari penjualan tersebut bulan ini?", "o": ["70 juta", "100 juta", "40 juta", "60 juta"], "a": 3},
    {"q": "Penjualan kredit bulan ini Rp100 juta. Bila 75 persen tertagih pada bulan yang sama, berapa kas yang diterima dari penjualan tersebut bulan ini?", "o": ["25 juta", "75 juta", "100 juta", "85 juta"], "a": 1},
    {"q": "Penjualan kredit bulan ini Rp120 juta. Bila 80 persen tertagih pada bulan yang sama, berapa kas yang diterima dari penjualan tersebut bulan ini?", "o": ["106 juta", "24 juta", "96 juta", "120 juta"], "a": 2},
    {"q": "Penjualan kredit bulan ini Rp120 juta. Bila 75 persen tertagih pada bulan yang sama, berapa kas yang diterima dari penjualan tersebut bulan ini?", "o": ["120 juta", "90 juta", "30 juta", "100 juta"], "a": 1},
    {"q": "Investasi Rp100 juta menghasilkan arus kas Rp50 juta per tahun. Payback Period proyek adalah...", "o": ["0.5 tahun", "3.5 tahun", "1.2 tahun", "2 tahun"], "a": 3},
    {"q": "Investasi Rp100 juta menghasilkan arus kas Rp25 juta per tahun. Payback Period proyek adalah...", "o": ["0.25 tahun", "4 tahun", "5.5 tahun", "3.2 tahun"], "a": 1},
    {"q": "Investasi Rp200 juta menghasilkan arus kas Rp25 juta per tahun. Payback Period proyek adalah...", "o": ["7.2 tahun", "8 tahun", "9.5 tahun", "0.12 tahun"], "a": 1},
    {"q": "Investasi Rp120 juta menghasilkan arus kas Rp30 juta per tahun. Payback Period proyek adalah...", "o": ["4 tahun", "5.5 tahun", "3.2 tahun", "0.25 tahun"], "a": 0},
    {"q": "Investasi Rp200 juta menghasilkan arus kas Rp50 juta per tahun. Payback Period proyek adalah...", "o": ["3.2 tahun", "5.5 tahun", "0.25 tahun", "4 tahun"], "a": 3},
    {"q": "Investasi Rp120 juta menghasilkan arus kas Rp40 juta per tahun. Payback Period proyek adalah...", "o": ["3 tahun", "4.5 tahun", "2.2 tahun", "0.33 tahun"], "a": 0},
    {"q": "Investasi Rp150 juta menghasilkan arus kas Rp50 juta per tahun. Payback Period proyek adalah...", "o": ["4.5 tahun", "0.33 tahun", "3 tahun", "2.2 tahun"], "a": 2},
    {"q": "Proyek investasi Rp100 juta menghasilkan arus kas Rp40 juta per tahun selama 3 tahun, biaya modal 10 persen. Berdasarkan NPV, proyek sebaiknya...", "o": ["Ditunda tanpa alasan", "Diterima tanpa perhitungan", "Diterima karena NPV negatif", "Ditolak karena NPV negatif"], "a": 3},
    {"q": "Proyek investasi Rp120 juta menghasilkan arus kas Rp40 juta per tahun selama 3 tahun, biaya modal 12 persen. Berdasarkan NPV, proyek sebaiknya...", "o": ["Diterima tanpa perhitungan", "Ditolak karena NPV negatif", "Ditunda tanpa alasan", "Diterima karena NPV negatif"], "a": 1},
    {"q": "Proyek investasi Rp100 juta menghasilkan arus kas Rp50 juta per tahun selama 3 tahun, biaya modal 12 persen. Berdasarkan NPV, proyek sebaiknya...", "o": ["Ditolak karena NPV positif", "Diterima karena NPV positif", "Ditunda tanpa alasan", "Diterima tanpa perhitungan"], "a": 1},
    {"q": "Proyek investasi Rp120 juta menghasilkan arus kas Rp50 juta per tahun selama 3 tahun, biaya modal 12 persen. Berdasarkan NPV, proyek sebaiknya...", "o": ["Ditolak karena NPV positif", "Ditunda tanpa alasan", "Diterima karena NPV positif", "Diterima tanpa perhitungan"], "a": 2},
    {"q": "Proyek investasi Rp120 juta menghasilkan arus kas Rp50 juta per tahun selama 4 tahun, biaya modal 10 persen. Berdasarkan NPV, proyek sebaiknya...", "o": ["Ditolak karena NPV positif", "Diterima tanpa perhitungan", "Ditunda tanpa alasan", "Diterima karena NPV positif"], "a": 3},
    {"q": "Proyek investasi Rp100 juta menghasilkan arus kas Rp50 juta per tahun selama 3 tahun, biaya modal 10 persen. Berdasarkan NPV, proyek sebaiknya...", "o": ["Diterima karena NPV positif", "Ditunda tanpa alasan", "Ditolak karena NPV positif", "Diterima tanpa perhitungan"], "a": 0},
    {"q": "Biaya yang dianggarkan Rp117 juta, realisasi biaya aktual Rp120 juta. Varian sebesar Rp3 juta ini tergolong...", "o": ["Tidak ada varian", "Unfavorable (tidak menguntungkan)", "Favorable (menguntungkan)", "Tidak dapat dinilai"], "a": 1},
    {"q": "Pendapatan yang dianggarkan Rp116 juta, realisasi pendapatan aktual Rp99 juta. Varian sebesar Rp17 juta ini tergolong...", "o": ["Tidak dapat dinilai", "Favorable (menguntungkan)", "Tidak ada varian", "Unfavorable (tidak menguntungkan)"], "a": 3},
    {"q": "Pendapatan yang dianggarkan Rp104 juta, realisasi pendapatan aktual Rp72 juta. Varian sebesar Rp32 juta ini tergolong...", "o": ["Tidak dapat dinilai", "Unfavorable (tidak menguntungkan)", "Favorable (menguntungkan)", "Tidak ada varian"], "a": 1},
    {"q": "Pendapatan yang dianggarkan Rp95 juta, realisasi pendapatan aktual Rp43 juta. Varian sebesar Rp52 juta ini tergolong...", "o": ["Tidak dapat dinilai", "Unfavorable (tidak menguntungkan)", "Favorable (menguntungkan)", "Tidak ada varian"], "a": 1},
    {"q": "Pendapatan yang dianggarkan Rp78 juta, realisasi pendapatan aktual Rp93 juta. Varian sebesar Rp15 juta ini tergolong...", "o": ["Tidak dapat dinilai", "Unfavorable (tidak menguntungkan)", "Tidak ada varian", "Favorable (menguntungkan)"], "a": 3},
]

assert len(UAS_BANK) == 100, f"Bank soal harus 100, saat ini {len(UAS_BANK)}"
